version: "3.9"
services:
  chancho:
    build: .
    ports:
      - "3000:3000"
    links:
      - tarzan
  tarzan:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data
      
volumes:
  mongo-data: